package dev.dyclaim;

import dev.dyclaim.manager.*;
import org.bukkit.entity.Player;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class MarketAndConfigTest extends ManagerFixture {
    @BeforeEach void config(){values.set("confirmations.clickable-buttons",false);values.set("market.enabled",true);}
    @Test void doubleBuyPaysOnlyOnceAndClearsSellerTrust(){var chunk=chunk(0,0);Player owner=player("Owner",chunk),first=player("First",chunk),second=player("Second",chunk);claims.claimChunk(owner,chunk);claims.getClaimAt(chunk).grant(UUID.randomUUID(),0);features.handle(owner,new String[]{"market","list","1000"});features.handle(first,new String[]{"market","buy"});features.handle(second,new String[]{"market","buy"});assertTrue(confirmations.confirm(first.getUniqueId()));assertFalse(confirmations.confirm(second.getUniqueId()));assertEquals(first.getUniqueId(),claims.getClaimAt(chunk).getOwnerUUID());assertTrue(claims.getClaimAt(chunk).getTrustGrants().isEmpty());verify(economy,times(1)).withdraw(first.getUniqueId(),1000);verify(economy,never()).withdraw(second.getUniqueId(),1000);verify(economy,times(1)).deposit(owner.getUniqueId(),950);}
    @Test void staleListingAndTaxChangesCannotPay(){var chunk=chunk(0,0);Player owner=player("Owner",chunk),buyer=player("Buyer",chunk);claims.claimChunk(owner,chunk);features.handle(owner,new String[]{"market","list","1000"});features.handle(buyer,new String[]{"market","buy"});values.set("market.tax-percent",10);confirmations.confirm(buyer.getUniqueId());assertEquals(owner.getUniqueId(),claims.getClaimAt(chunk).getOwnerUUID());verify(economy,never()).withdraw(any(UUID.class),anyDouble());}
    @Test void buyerLimitAndBanAreCheckedAtAcceptance(){var chunk=chunk(0,0);Player owner=player("Owner",chunk),buyer=player("Buyer",chunk);claims.claimChunk(owner,chunk);features.handle(owner,new String[]{"market","list","1000"});features.handle(buyer,new String[]{"market","buy"});values.set("claim.max-claims-per-player",1);claims.claimChunk(buyer,chunk(3,0));confirmations.confirm(buyer.getUniqueId());assertEquals(owner.getUniqueId(),claims.getClaimAt(chunk).getOwnerUUID());verify(economy,never()).withdraw(any(UUID.class),anyDouble());}
    @Test void temporaryClaimBanPersistsWithoutBecomingServerBan(){Player admin=player("Admin",chunk(0,0)),target=player("Target",chunk(1,0));when(admin.hasPermission("dyclaim.admin")).thenReturn(true);features.handle(admin,new String[]{"admin","ban","Target","2d"});assertTrue(features.isClaimBanned(target.getUniqueId()));assertTrue(new FeatureManager(plugin).isClaimBanned(target.getUniqueId()));features.handle(admin,new String[]{"admin","unban","Target"});assertFalse(features.isClaimBanned(target.getUniqueId()));}
    @Test void defaultConfigValidatesAndInvalidForcedPolicyRejects(){ConfigManager.validate(values);values.set("protection.visitor-doors.forced-value","yes");assertThrows(IllegalArgumentException.class,()->ConfigManager.validate(values));}
    @Test void validationRejectsUnsafeNumbersAndDurations(){for(String key:List.of("confirmations.timeout-seconds","admin.purge.batch-size","warnings.window-seconds","protection.mobs.remove-on-entry.batch-size")){Object old=values.get(key);values.set(key,0);assertThrows(IllegalArgumentException.class,()->ConfigManager.validate(values));values.set(key,old);}values.set("market.tax-percent",Double.NaN);assertThrows(IllegalArgumentException.class,()->ConfigManager.validate(values));}
    @Test void playerLanguagePersists(){Player target=player("Target",chunk(0,0));features.handle(target,new String[]{"lang","tr"});assertEquals("tr",new FeatureManager(plugin).language(target.getUniqueId()));features.handle(target,new String[]{"lang","auto"});assertNull(features.language(target.getUniqueId()));}
    @Test void disabledFeaturesDoNotStartBackgroundTasks(){features.reloadTasks();verify(scheduler,never()).runTaskTimer(eq(plugin),any(Runnable.class),anyLong(),anyLong());}
    @Test void coownerCannotOfferTransfer(){var chunk=chunk(0,0);Player owner=player("Owner",chunk),co=player("Co",chunk),target=player("Target",chunk);claims.claimChunk(owner,chunk);claims.getClaimAt(chunk).setCoowner(co.getUniqueId());claims.rebuildPlayerIndex();features.handle(co,new String[]{"transfer","Target"});assertFalse(confirmations.hasPending(target.getUniqueId()));assertEquals(owner.getUniqueId(),claims.getClaimAt(chunk).getOwnerUUID());}
    @Test void narrowDoorTrustDoesNotPermitContainersOrBuilding(){var chunk=chunk(0,0);Player owner=player("Owner",chunk),visitor=player("Visitor",chunk);claims.claimChunk(owner,chunk);var c=claims.getClaimAt(chunk);c.grant(visitor.getUniqueId(),0);c.getTrustGrants().get(visitor.getUniqueId()).permissions=new HashSet<>(Set.of("doors"));assertTrue(access.allows(visitor,c,"doors"));assertFalse(access.allows(visitor,c,"containers"));assertFalse(access.allows(visitor,c,"build"));}
}
