const mf=require('mineflayer'),fs=require('fs'),path=require('path'),yaml=require('yaml'),assert=require('assert');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const dir=path.resolve(process.env.DYCLAIM_TEST_SERVER || path.join(__dirname,'../../.local/server'));const history={};const bots=[];const results=[];
function data(){return JSON.parse(fs.readFileSync(path.join(dir,'plugins/DyClaim/claims.json'),'utf8')).claims}
async function consoleCmd(text){fs.appendFileSync(path.join(dir,'commands.txt'),text+'\n');await sleep(500)}
async function cmd(bot,text){bot.chat(text);await sleep(700)}
async function connect(name){const bot=mf.createBot({host:'127.0.0.1',port:Number(process.env.DYCLAIM_TEST_PORT || 25575),username:name,version:process.env.DYCLAIM_TEST_CLIENT_VERSION || '1.20.4',auth:'offline'});history[name]=[];bot.on('messagestr',msg=>{history[name].push(msg);console.log(name+': '+msg)});bot.on('error',err=>console.log(err));bots.push(bot);await new Promise(r=>bot.once('spawn',r));return bot}
async function check(name,action){await action();results.push(name);console.log('PASS '+name)}
async function config(a,mutate){const file=path.join(dir,'plugins/DyClaim/config.yml');const conf=yaml.parse(fs.readFileSync(file,'utf8'));mutate(conf);fs.writeFileSync(file,yaml.stringify(conf));await consoleCmd('op AlphaTest');await cmd(a,'/claim admin reload');await consoleCmd('deop AlphaTest')}
(async()=>{
 const a=await connect('AlphaTest'),b=await connect('BetaTest'),c=await connect('VisitorTest');
 await consoleCmd('gamemode creative AlphaTest');await consoleCmd('gamemode creative BetaTest');await consoleCmd('gamemode creative VisitorTest');
 await consoleCmd('fill 0 63 0 127 63 31 stone');await consoleCmd('tp AlphaTest 8 64 8');await consoleCmd('tp BetaTest 40 64 8');await consoleCmd('tp VisitorTest 10 64 8');
 await check('claim-without-buttons',async()=>{await config(a,cfg=>{cfg.confirmations['clickable-buttons']=false});await cmd(a,'/claim');await cmd(a,'/confirm');assert(data()['world:0:0'])});
 await check('temporary-narrow-trust',async()=>{await cmd(a,'/claim trust VisitorTest 1m');for(const right of ['build','containers','trapdoors','redstone','entities','teleport'])await cmd(a,'/claim trustperm VisitorTest '+right+' deny');await sleep(1200);const grants=data()['world:0:0'].trustGrants;const grant=grants[c.player.uuid];assert(grant.expiresAt>Date.now());assert.deepEqual(grant.permissions,['doors'])});
 await check('name-safe-spawn-and-tp',async()=>{await cmd(a,'/claim name Sunrise');await cmd(a,'/claim setspawn');await sleep(1200);assert.equal(data()['world:0:0'].name,'Sunrise');assert(data()['world:0:0'].spawnX!==undefined);await consoleCmd('tp AlphaTest 24 64 8');await cmd(a,'/claim tp Sunrise');await sleep(3800);assert.equal(Math.floor(a.entity.position.x/16),0)});
 await check('coowner-consent-and-sale-denial',async()=>{await cmd(a,'/claim coowner add BetaTest');assert(!data()['world:0:0'].coowner);await cmd(b,'/confirm');assert.equal(data()['world:0:0'].coowner,b.player.uuid);await consoleCmd('tp BetaTest 8 64 8');const start=history.BetaTest.length;await cmd(b,'/claim sell');assert(history.BetaTest.slice(start).some(s=>s.includes('not the owner')));await cmd(a,'/claim coowner remove');await sleep(1200);assert(!data()['world:0:0'].coowner)});
 await check('transfer-consent-clears-access',async()=>{await cmd(a,'/claim transfer BetaTest');assert.equal(data()['world:0:0'].ownerName,'AlphaTest');await cmd(b,'/confirm');const claim=data()['world:0:0'];assert.equal(claim.ownerName,'BetaTest');assert.equal(Object.keys(claim.trustGrants).length,0);assert(!claim.coowner)});
 await check('villager-default-blocks-owner',async()=>{await consoleCmd('summon villager 9 64 8 {NoAI:1b,PersistenceRequired:1b,CustomName:\'{"text":"SmokeVillager"}\'}');await sleep(700);const villager=Object.values(b.entities).find(e=>e.name==='villager');assert(villager);const start=history.BetaTest.length;b.attack(villager);await sleep(700);assert(history.BetaTest.slice(start).some(s=>s.includes('cannot damage villagers')))});
 await check('manual-language-persistence',async()=>{await cmd(b,'/claim lang tr');await cmd(b,'/claim info');assert(history.BetaTest.some(s=>s.includes('Sahip: BetaTest')));assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'plugins/DyClaim/state.json'),'utf8')).languages[b.player.uuid],'tr');await cmd(b,'/claim lang auto')});
 await check('warnings-cooldown-and-entry-ban',async()=>{await config(a,cfg=>{cfg.warnings.enabled=true;cfg.warnings['cooldown-seconds']=1;cfg.warnings['window-seconds']=10;cfg.warnings.punishment.type='claim-entry-ban'});await consoleCmd('tp VisitorTest 10 64 8');await cmd(b,'/claim warn VisitorTest');await cmd(b,'/claim warn VisitorTest');await sleep(700);await cmd(b,'/claim warn VisitorTest');await sleep(700);await cmd(b,'/claim warn VisitorTest');await sleep(1000);const state=JSON.parse(fs.readFileSync(path.join(dir,'plugins/DyClaim/state.json'),'utf8'));assert(Object.values(state.warnings).some(w=>w.stage==='applied'&&w.mode==='claim-entry-ban'));assert(Math.floor(c.entity.position.x/16)!==0||Math.floor(c.entity.position.z/16)!==0)});
 await check('acquisition-ban-covers-normal-and-coowner',async()=>{await consoleCmd('op AlphaTest');await cmd(a,'/claim admin ban VisitorTest 2d');await consoleCmd('deop AlphaTest');await consoleCmd('tp VisitorTest 88 64 8');const before=Object.keys(data()).length;await cmd(c,'/claim');await cmd(c,'/confirm');assert.equal(Object.keys(data()).length,before);await cmd(b,'/claim coowner add VisitorTest');assert(!data()['world:0:0'].coowner)});
 await check('invalid-config-reload-retains-valid-policy',async()=>{await consoleCmd('op AlphaTest');const file=path.join(dir,'plugins/DyClaim/config.yml');const prior=fs.readFileSync(file,'utf8');const cfg=yaml.parse(prior);cfg['confirmation-timeout']=-1;fs.writeFileSync(file,yaml.stringify(cfg));const start=history.AlphaTest.length;await cmd(a,'/claim admin reload');assert(history.AlphaTest.slice(start).some(s=>s.includes('previous valid')));fs.writeFileSync(file,prior);await cmd(a,'/claim admin reload');await consoleCmd('deop AlphaTest')});
 await check('auto-requires-explicit-free-opt-in',async()=>{await consoleCmd('tp AlphaTest 72 64 8');const before=history.AlphaTest.length;await cmd(a,'/claim auto on');assert(history.AlphaTest.slice(before).some(s=>s.includes('unavailable')));await config(a,cfg=>{cfg['auto-claim'].enabled=true;cfg['auto-claim']['require-economy']=false;cfg['auto-claim']['allow-zero-price']=true});await cmd(a,'/claim auto on');await a.look(-Math.PI/2,0,true);a.setControlState('forward',true);await sleep(3500);a.setControlState('forward',false);await sleep(1200);assert(Object.values(data()).some(claim=>claim.ownerName==='AlphaTest'&&claim.chunkX>=5));await cmd(a,'/claim auto off')});
 await config(a,cfg=>{cfg.confirmations['clickable-buttons']=true;cfg.warnings.enabled=false;cfg.warnings['cooldown-seconds']=60;cfg.warnings['window-seconds']=180;cfg.warnings.punishment.type='server-ban';cfg['auto-claim'].enabled=false;cfg['auto-claim']['require-economy']=true;cfg['auto-claim']['allow-zero-price']=false});
 fs.writeFileSync(path.join(__dirname,'features-result.json'),JSON.stringify({results,history,claims:data()},null,2));console.log('ALL FEATURE CHECKS PASSED '+results.length);bots.forEach(b=>b.quit());await sleep(500);
})().then(()=>process.exit(0)).catch(err=>{fs.writeFileSync(path.join(__dirname,'features-failed.json'),JSON.stringify({results,history,error:err.stack},null,2));console.error(err);bots.forEach(b=>b.quit());process.exit(1)});


